"use client";

import Link from "next/link";
import { useState } from "react";

type Preview = { row: number; duplicateOf: string | null; errors: string[]; tradeName: string; city: string };
type ImportResponse = { total?: number; valid?: number; duplicates?: number; invalid?: number; preview?: Preview[]; imported?: number; skippedDuplicates?: number; error?: string };

const example = `Nome fantasia;Razão social;Cidade;Região;Telefone;WhatsApp;E-mail;Site;Programas;Destinos;Potencial\nAgência exemplo;Razão social exemplo;Porto Alegre;Metropolitana;(51) 0000-0000;;contato@exemplo.com;https://exemplo.com;Curso de idiomas;Canadá;C`;

export default function ImportWorkspace() {
  const [fileName, setFileName] = useState("");
  const [csv, setCsv] = useState("");
  const [result, setResult] = useState<ImportResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("");
  async function readFile(file: File | undefined) { if (!file) return; setFileName(file.name); setCsv(await file.text()); setResult(null); setMessage(""); }
  async function preview() { setLoading(true); setMessage(""); const response = await fetch("/api/import/agencies", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv }) }); const data = await response.json() as ImportResponse; setResult(data); setMessage(response.ok ? "Validação concluída. Nenhum registro foi alterado." : data.error ?? "Não foi possível validar o arquivo."); setLoading(false); }
  async function confirmImport() { if (!result?.valid || !window.confirm(`Importar ${result.valid} registros novos? Duplicados e linhas inválidas serão ignorados.`)) return; setLoading(true); const response = await fetch("/api/import/agencies", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv, confirm: true }) }); const data = await response.json() as ImportResponse; setMessage(response.ok ? `${data.imported ?? 0} agências importadas. ${data.skippedDuplicates ?? 0} duplicadas preservadas.` : data.error ?? "Não foi possível concluir a importação."); setLoading(false); }
  return <div className="workspace-shell"><header className="workspace-heading"><div><span className="eyebrow">Base de dados</span><h1>Importação controlada</h1><p>Valide um CSV, veja duplicidades e só confirme depois de revisar. Nenhuma ficha existente é sobrescrita.</p></div><Link className="inline-link" href="/admin">Voltar ao cadastro <span>→</span></Link></header><section className="workspace-card import-card"><div className="import-instructions"><h2>Como importar</h2><p>Use a primeira linha como cabeçalho. Os campos reconhecidos incluem nome, cidade, região, contatos, programas, destinos e potencial.</p><button type="button" className="text-button" onClick={() => { setFileName("modelo.csv"); setCsv(example); setResult(null); }}>Carregar exemplo de estrutura</button></div><label className="file-drop"><input type="file" accept=".csv,text/csv" onChange={(event) => readFile(event.target.files?.[0])} /><strong>{fileName || "Escolher arquivo CSV"}</strong><small>Até 2 MB · UTF-8, separado por ponto e vírgula, vírgula ou tabulação</small></label><div className="import-actions"><button className="button primary" type="button" disabled={!csv || loading} onClick={preview}>{loading ? "Validando…" : "Validar arquivo"}</button>{result?.valid ? <button className="button dark" type="button" disabled={loading} onClick={confirmImport}>Confirmar importação ({result.valid})</button> : null}</div>{message && <p className="save-status">{message}</p>}</section>{result && <section className="import-result"><div className="report-grid"><article><span>Linhas lidas</span><strong>{result.total ?? 0}</strong></article><article><span>Prontas para importar</span><strong>{result.valid ?? result.imported ?? 0}</strong></article><article><span>Duplicadas</span><strong>{result.duplicates ?? result.skippedDuplicates ?? 0}</strong></article><article><span>Inválidas</span><strong>{result.invalid ?? 0}</strong></article></div>{result.preview?.length ? <div className="lead-table"><div className="lead-table-head"><span>Prévia da validação</span><small>Linhas existentes são preservadas</small></div>{result.preview.map((item) => <article key={item.row}><div><strong>Linha {item.row} · {item.tradeName}</strong><small>{item.city}</small></div><span className={item.errors.length ? "import-invalid" : item.duplicateOf ? "import-duplicate" : "import-valid"}>{item.errors.join(", ") || (item.duplicateOf ? `Duplicada de ${item.duplicateOf}` : "Pronta")}</span></article>)}</div> : null}</section>}</div>;
}
