"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Report = { generatedAt: string; role: string; totals: { agencies: number; contacts: number; tasks: number; openTasks: number; leads: number; pipeline: number }; status: Array<{ label: string; value: number }>; cities: Array<{ label: string; value: number }>; region: Array<{ label: string; value: number }>; events: Array<{ label: string; value: number }> };

function money(value: number) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(value); }
function downloadCsv(report: Report) { const rows = [["Indicador", "Valor"], ["Agências", report.totals.agencies], ["Contatos", report.totals.contacts], ["Tarefas", report.totals.tasks], ["Tarefas abertas", report.totals.openTasks], ["Leads", report.totals.leads], ["Pipeline", report.totals.pipeline], ...report.status.map((item) => [`Status · ${item.label}`, item.value]), ...report.cities.map((item) => [`Cidade · ${item.label}`, item.value])]; const csv = rows.map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(";")).join("\n"); const blob = new Blob([`\ufeff${csv}`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `relatorio-mapa-agencias-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); }

export default function ReportsWorkspace() {
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/reports").then(async (response) => { if (!response.ok) throw new Error(); return await response.json() as Report; }).then(setReport).catch(() => setError("Não foi possível carregar o relatório.")); }, []);
  if (error) return <div className="empty-state">{error}</div>;
  if (!report) return <div className="loading-panel">Consolidando relatório comercial…</div>;
  const maxStatus = Math.max(1, ...report.status.map((item) => item.value));
  return <div className="workspace-shell"><header className="workspace-heading"><div><span className="eyebrow">Gestão e desempenho</span><h1>Relatórios</h1><p>Uma leitura exportável da operação, do funil e das conversões registradas.</p></div><div className="workspace-heading-actions"><button className="button primary" onClick={() => downloadCsv(report)}>Exportar CSV <span>↓</span></button><Link className="inline-link" href="/dashboard">Dashboard <span>→</span></Link></div></header><div className="report-metric-grid"><article><span>Agências</span><strong>{report.totals.agencies}</strong></article><article><span>Contatos registrados</span><strong>{report.totals.contacts}</strong></article><article><span>Leads públicos</span><strong>{report.totals.leads}</strong></article><article><span>Pipeline estimado</span><strong>{money(report.totals.pipeline)}</strong></article></div><div className="report-grid"><section className="report-card"><div className="report-card-head"><div><span className="eyebrow">Funil</span><h2>Status comercial</h2></div></div><div className="report-bars">{report.status.map((item) => <div key={item.label}><span>{item.label}</span><i><b style={{ width: `${Math.max(3, item.value / maxStatus * 100)}%` }} /></i><strong>{item.value}</strong></div>)}</div></section><section className="report-card"><span className="eyebrow">Cobertura</span><h2>Potencial por região</h2><div className="report-list">{report.region.map((item) => <div key={item.label}><span>{item.label}</span><b>{item.value.toLocaleString("pt-BR")}</b></div>)}</div></section><section className="report-card"><span className="eyebrow">Concentração</span><h2>Agências por cidade</h2><div className="report-list">{report.cities.map((item) => <div key={item.label}><span>{item.label}</span><b>{item.value}</b></div>)}</div></section><section className="report-card"><span className="eyebrow">Analytics interno</span><h2>Eventos nos últimos 30 dias</h2><div className="report-list">{report.events.length ? report.events.map((item) => <div key={item.label}><span>{item.label}</span><b>{item.value}</b></div>) : <p className="report-empty">Nenhum evento registrado ainda.</p>}</div></section></div><p className="report-footnote">Gerado em {new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(report.generatedAt))} · perfil {report.role}.</p></div>;
}
