"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { AccompanimentResponse } from "@/lib/types";

function countBy(items: string[]) { return [...items.reduce((map, label) => map.set(label, (map.get(label) ?? 0) + 1), new Map<string, number>()).entries()].sort((a, b) => b[1] - a[1]).map(([label, value]) => ({ label, value })); }
function downloadCsv(data: AccompanimentResponse) { const rows = [["Agência", "Cidade", "Região", "Tipo", "Status", "Prioridade", "Completude", "Último contato", "Próxima ação"], ...data.agencies.map((agency) => [agency.tradeName, agency.city, agency.region, agency.agencyKind, agency.accompanimentStatus ?? "Não analisada", agency.accompanimentPriority ?? "Sem prioridade definida", agency.completeness, agency.lastContactAt ?? "", agency.nextAction ?? ""])]; const csv = rows.map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(";")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: "text/csv;charset=utf-8" })); link.download = `acompanhamento-agencias-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); }

export default function ReportsWorkspace() {
  const [data, setData] = useState<AccompanimentResponse | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/acompanhamento", { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error(); return await response.json() as AccompanimentResponse; }).then(setData).catch(() => setError("Não foi possível carregar o relatório agora.")); }, []);
  if (error) return <div className="empty-state">{error}</div>;
  if (!data) return <div className="loading-panel"><strong>Preparando relatório…</strong><p>Consolidando registros de acompanhamento.</p></div>;
  const statuses = countBy(data.agencies.map((agency) => agency.accompanimentStatus ?? "Não analisada"));
  const regions = countBy(data.agencies.map((agency) => agency.region));
  const cities = countBy(data.agencies.map((agency) => agency.city)).slice(0, 12);
  return <div className="workspace-shell"><header className="workspace-heading"><div><span className="eyebrow">Resumo operacional</span><h1>Relatórios</h1><p>Uma leitura exportável da cobertura, da completude das fichas e das próximas ações.</p></div><div className="workspace-heading-actions"><button className="button primary" onClick={() => downloadCsv(data)}>Exportar CSV <span>↓</span></button><Link className="inline-link" href="/dashboard">Dashboard <span>→</span></Link></div></header><div className="report-metric-grid"><article><span>Agências no mapa</span><strong>{data.metrics.total.toLocaleString("pt-BR")}</strong><small>{data.filters.cities.length} municípios</small></article><article><span>Contatos realizados</span><strong>{data.metrics.contacted}</strong><small>{data.metrics.awaitingReply} aguardando retorno</small></article><article><span>Fichas incompletas</span><strong>{data.metrics.incomplete}</strong><small>{data.metrics.notAnalyzed} ainda não analisadas</small></article><article><span>Ações vencidas</span><strong>{data.metrics.overdue}</strong><small>{data.tasks.filter((task) => task.status === "Aberta").length} ações abertas</small></article></div><div className="report-grid"><section className="report-card"><div className="report-card-head"><div><span className="eyebrow">Acompanhamento</span><h2>Status das fichas</h2></div></div><div className="report-bars">{statuses.map((item) => <div key={item.label}><span>{item.label}</span><i><b style={{ width: `${Math.max(3, item.value / Math.max(1, statuses[0]?.value ?? 1) * 100)}%` }} /></i><strong>{item.value}</strong></div>)}</div></section><section className="report-card"><span className="eyebrow">Cobertura</span><h2>Agências por região</h2><div className="report-list">{regions.slice(0, 10).map((item) => <div key={item.label}><span>{item.label}</span><b>{item.value.toLocaleString("pt-BR")}</b></div>)}</div></section><section className="report-card"><span className="eyebrow">Concentração</span><h2>Agências por cidade</h2><div className="report-list">{cities.map((item) => <div key={item.label}><span>{item.label}</span><b>{item.value}</b></div>)}</div></section><section className="report-card"><span className="eyebrow">Agenda</span><h2>Próximas ações</h2><div className="report-list">{data.tasks.filter((task) => task.status === "Aberta").slice(0, 10).map((task) => <div key={task.id}><span>{task.agencyName} · {task.activityType}</span><b>{task.dueAt.slice(0, 10)}</b></div>)}{!data.tasks.length && <p className="report-empty">Nenhuma ação agendada.</p>}</div></section></div></div>;
}

