"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import type { UserRole, UserRoleRecord } from "@/lib/types";
import { userRoles } from "@/lib/types";

export default function UsersWorkspace() {
  const [users, setUsers] = useState<UserRoleRecord[]>([]); const [form, setForm] = useState({ email: "", displayName: "", role: "vendedor" as UserRole }); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/users"); if (response.ok) setUsers(await response.json() as UserRoleRecord[]); else setMessage("Não foi possível carregar os usuários."); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) { const error = await response.json() as { error?: string }; setMessage(error.error ?? "Não foi possível salvar."); return; } setForm({ email: "", displayName: "", role: "vendedor" }); setMessage("Perfil criado."); await load(); }
  async function changeRole(user: UserRoleRecord, role: UserRole) { await fetch("/api/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...user, role }) }); await load(); }
  return <div className="workspace-shell"><header className="workspace-heading"><div><span className="eyebrow">Acesso e governança</span><h1>Usuários e permissões</h1><p>Defina o que cada pessoa pode consultar e editar dentro do workspace comercial.</p></div><Link className="inline-link" href="/dashboard">Voltar ao dashboard <span>→</span></Link></header><div className="users-grid"><section className="workspace-card"><span className="eyebrow">Novo acesso</span><h2>Adicionar pessoa</h2><form className="stack-form" onSubmit={submit}><label><span>Nome</span><input required value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} /></label><label><span>E-mail da conta</span><input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label><span>Perfil</span><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as UserRole })}>{userRoles.map((role) => <option key={role} value={role}>{role === "admin" ? "Administrador" : role === "gestor" ? "Gestor comercial" : role === "vendedor" ? "Vendedor" : "Usuário de consulta"}</option>)}</select></label><button className="button primary">Salvar acesso</button><span className="save-status">{message}</span></form></section><section className="workspace-card"><span className="eyebrow">Pessoas autorizadas</span><h2>{users.length} perfis</h2><div className="user-table">{users.map((user) => <article key={user.userKey}><div><strong>{user.displayName}</strong><small>{user.email}{user.login ? ` · @${user.login}` : ""}</small></div><select value={user.role} onChange={(e) => changeRole(user, e.target.value as UserRole)}>{userRoles.map((role) => <option key={role}>{role}</option>)}</select></article>)}{users.length === 0 && <p className="report-empty">Nenhum perfil registrado além do administrador atual.</p>}</div></section></div></div>;
}
