import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const agencies = sqliteTable("agencies", {
  id: text("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  legalName: text("legal_name"),
  tradeName: text("trade_name").notNull(),
  city: text("city").notNull(),
  region: text("region").notNull(),
  address: text("address"),
  phone: text("phone"),
  email: text("email"),
  website: text("website"),
  instagram: text("instagram"),
  linkedin: text("linkedin"),
  directors: text("directors"),
  owners: text("owners"),
  commercialManager: text("commercial_manager"),
  exchangeLead: text("exchange_lead"),
  programs: text("programs").notNull().default("[]"),
  belta: integer("belta"),
  units: integer("units").notNull().default(1),
  audienceProfile: text("audience_profile").notNull(),
  commercialPotential: text("commercial_potential").notNull(),
  notes: text("notes"),
  verificationStatus: text("verification_status").notNull(),
  sourceUrl: text("source_url"),
  sourceLabel: text("source_label"),
  verifiedAt: text("verified_at"),
  updatedAt: text("updated_at").notNull(),
  state: text("state").notNull().default("RS"),
  neighborhood: text("neighborhood"),
  cep: text("cep"),
  whatsapp: text("whatsapp"),
  facebook: text("facebook"),
  network: text("network"),
  commercialStatus: text("commercial_status").notNull().default("Não contatada"),
  assignedTo: text("assigned_to"),
  opportunityScore: integer("opportunity_score").notNull().default(0),
  estimatedValue: real("estimated_value"),
  firstContactAt: text("first_contact_at"),
  lastContactAt: text("last_contact_at"),
  nextFollowUpAt: text("next_follow_up_at"),
  lossReason: text("loss_reason"),
  googleRating: real("google_rating"),
  googleReviewCount: integer("google_review_count"),
  isFranchise: integer("is_franchise"),
  destinations: text("destinations").notNull().default("[]"),
  exchangeTypes: text("exchange_types").notNull().default("[]"),
  description: text("description"),
  hours: text("hours"),
  logoUrl: text("logo_url"),
  competitors: text("competitors"),
  productsOfInterest: text("products_of_interest"),
  needs: text("needs"),
  latitude: real("latitude"),
  longitude: real("longitude"),
});

export const contacts = sqliteTable("contacts", {
  id: text("id").primaryKey(),
  agencyId: text("agency_id").notNull(),
  contactDate: text("contact_date").notNull(),
  channel: text("channel").notNull(),
  contactName: text("contact_name"),
  summary: text("summary").notNull(),
  nextStep: text("next_step"),
  createdAt: text("created_at").notNull(),
  interactionType: text("interaction_type"),
  contactTime: text("contact_time"),
  result: text("result"),
  nextContactAt: text("next_contact_at"),
  createdBy: text("created_by"),
});

export const agencyStatusHistory = sqliteTable("agency_status_history", {
  id: text("id").primaryKey(),
  agencyId: text("agency_id").notNull(),
  previousStatus: text("previous_status"),
  newStatus: text("new_status").notNull(),
  userEmail: text("user_email"),
  note: text("note"),
  changedAt: text("changed_at").notNull(),
});

export const tasks = sqliteTable("tasks", {
  id: text("id").primaryKey(),
  agencyId: text("agency_id").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  assignedTo: text("assigned_to"),
  dueAt: text("due_at").notNull(),
  priority: text("priority").notNull().default("Média"),
  status: text("status").notNull().default("Aberta"),
  activityType: text("activity_type").notNull().default("Follow-up"),
  notes: text("notes"),
  completedAt: text("completed_at"),
  createdAt: text("created_at").notNull(),
  createdBy: text("created_by"),
});

export const githubSessions = sqliteTable("github_sessions", {
  sessionId: text("session_id").primaryKey(),
  githubId: text("github_id").notNull(),
  login: text("login").notNull(),
  displayName: text("display_name").notNull(),
  email: text("email"),
  avatarUrl: text("avatar_url"),
  createdAt: text("created_at").notNull(),
  expiresAt: text("expires_at").notNull(),
});
